#!/bin/csh -f

set nonomatch

setenv D "$1:h"
cd "$D"
setenv RM "$1:t"

if(-e "$RM") then
	grep -q "Auto generated " "$RM"
	if($status) then
		# Non auto file exists
		touch "$RM"
		exit 0
	endif
endif

setenv TMP `mktemp -u`.md
cat << END > "$TMP"
# $D

## Trademark

This is an open source project, but bear in mind you cannot sell boards bearing the Andrews & Arnold Ltd name, the A&A logo, the registered trademark AJK logo, or the GS1 allocated EANs assigned to Andrews & Arnold Ltd.

END
set stl=(*.stl)
set pcb=(*.kicad_pcb)

if("$pcb" != '*.kicad_pcb') then
	echo "## PCB Designs" >> "$TMP"
	echo "" >> "$TMP"
	echo "These files are for use with [KiCAD](https://www.kicad.org)." >> "$TMP"
	echo "" >> "$TMP"
	foreach p ($pcb)
		echo "- [$p:r]($p:r.kicad_pro)" >> "$TMP"
	endif
endif


if("$stl" != '*.stl') then
	echo "## 3D" >> "$TMP"
	echo "" >> "$TMP"
	echo "3D case designs are normally automatically created from the PCB so as to ensure correct details and placement of apertures, etc." >> "$TMP"
	echo "" >> "$TMP"
	set c=0;
	foreach s ($stl)
		echo "import("'"'"$s:t"'"'");" >> "$s:r.scad"
		/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD -o $s:r.png "$s:r.scad" --backend GCAL
		rm -f "$s:r.scad"
	end
	foreach s ($stl)
		setenv N `echo "$s" | sed 's/[BT].stl$//'`
		if("$N" != "$s" && "$s" != "${N}T.stl" && -e "${N}B.stl" && -e "${N}T.stl") then
			@ c = $c + 1
			if($c == 1) then
				echo "|Design|Bottom|---|Top|---|" >> "$TMP"
				echo "|------|------|---|---|---|" >> "$TMP"
			endif
			echo "|$N|[${N}B](${N}B.stl)|<img src='${N}B.png' size=15%>|[${N}T](${N}T.stl)|<img src='${N}T.png' size=15%>|" >> "$TMP"
		endif
	end
	if($c) then
		echo "" >> "$TMP"
	endif
	set c=0
	foreach s ($stl)
		setenv N `echo "$s" | sed 's/[BT].stl$//'`
		if("$N" == "$s" || ! -e "${N}B.stl" || ! -e "${N}T.stl") then
			@ c = $c + 1
			echo "- [$s:r]($s)" >> "$TMP"
		endif
	end
	if($c) then
		echo "" >> "$TMP"
	endif
endif

if("$pcb" != '*.kicad_pcb') then
	foreach p ($pcb)
		setenv BOARD "$p:r"
		echo "## Images" >> "$TMP"
		echo "" >> "$TMP"
		echo -n "<img src='$BOARD.png' width=32%>" >> "$TMP"
		echo -n "<img src='$BOARD-90.png' width=32%>" >> "$TMP"
		echo "<img src='$BOARD-bottom.png' width=32%>" >> "$TMP"
		if(-e "$BOARD-alt.png") then
			echo -n "<img src='$BOARD-alt.png' width=32%>" >> "$TMP"
			echo -n "<img src='$BOARD-alt-90.png' width=32%>" >> "$TMP"
			echo "<img src='$BOARD-alt-bottom.png' width=32%>" >> "$TMP"
			endif
		if(-e "$BOARD-panel.png") then
			echo -n "<img src='$BOARD-panel.png' width=49%>" >> "$TMP"
			echo "<img src='$BOARD-panel-bottom.png' width=49%>" >> "$TMP"
		endif
	end
endif
echo "" >> "$TMP"
echo "---" >> "$TMP"
echo "" >> "$TMP"
echo "*Auto generated $RM `date +%FT%T`*" >> "$TMP"
mv -f "$TMP" "$RM"
