#!/bin/csh -f

set nonomatch

setenv D "$1:h"
cd "$D"
setenv RM "$1:t"

if(-e "$RM") then
	grep -q "Auto generated " "$RM"
	if($status) then
		# Non auto file exists
		touch "$RM"
		exit 0
	endif
endif

setenv TMP `mktemp -u`.md
cat << END > "$TMP"
# $D

## Trademark

This project is subject to the licence in the LICENCE file, and even if that says it is an open source project, you cannot sell boards or cases bearing the Andrews & Arnold Ltd name, the A&A logo, the registered trademark AJK logo or other registered trademarks, or any GS1 allocated EANs/barcode assigned to Andrews & Arnold Ltd.

END
set stl=(*.stl)
set pcb=(*.kicad_pcb)

if("$pcb" != '*.kicad_pcb') then
	echo "## PCB Designs" >> "$TMP"
	echo "" >> "$TMP"
	echo "These files are for use with [KiCAD](https://www.kicad.org)." >> "$TMP"
	echo "" >> "$TMP"
	foreach p ($pcb)
		echo "- [$p:r]($p:r.kicad_pro)" >> "$TMP"
	endif
	echo "" >> "$TMP"
endif


if("$stl" != '*.stl') then
	echo "## 3D" >> "$TMP"
	echo "" >> "$TMP"
	echo "3D case designs are normally automatically created from the PCB so as to ensure correct details and placement of apertures, etc." >> "$TMP"
	echo "" >> "$TMP"
	set c=0;
	foreach s ($stl)
		echo "import("'"'"$s:t"'"'");" >> "x$s:r.scad"
		/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD --colorscheme=WhiteResin --autocenter --viewall --render --imgsize=4096,4096 -o "$s:r.png" "x$s:r.scad"
		magick "$s:r.png" -transparent '#4589cd' -resize 1024x1024 -trim -bordercolor None -border 10 "$s:r.png"
		rm -f "x$s:r.scad"
	end
	foreach s ($stl)
		setenv N `echo "$s" | sed 's/[BTC].stl$//'`
		if("$N" != "$s" && "$s" != "${N}B.stl" && "$s" != "${N}T.stl" && -e "${N}B.stl" && -e "${N}T.stl" && -e "${N}C.stl") then
			@ c = $c + 1
			if($c == 1) then
				echo "|Design|Bottom|Top|Combined|" >> "$TMP"
				echo "|------|------|---|--------|" >> "$TMP"
			endif
			echo "|$N|<a href='${N}B.stl'><img src='${N}B.png' size=15%></a>|<a href='${N}T.stl'><img src='${N}T.png' size=15%></a>|<a href='${N}C.stl'><img src='${N}C.png' size=15%></a>|" >> "$TMP"
		endif
	end
	if($c) then
		echo "" >> "$TMP"
	endif
	set c=0
	foreach s ($stl)
		setenv N `echo "$s" | sed 's/[BTC].stl$//'`
		if("$N" == "$s" || ! -e "${N}B.stl" || ! -e "${N}T.stl" || ! -e "${N}C.stl") then
			@ c = $c + 1
			echo "- [$s:r]($s)" >> "$TMP"
		endif
	end
	if($c) then
		echo "" >> "$TMP"
	endif
endif

if("$pcb" != '*.kicad_pcb') then
	foreach p ($pcb)
		setenv BOARD "$p:r"
		echo "## PCB Images" >> "$TMP"
		echo "" >> "$TMP"
		echo -n "<img src='$BOARD.png' width=32%>" >> "$TMP"
		echo -n "<img src='$BOARD-90.png' width=32%>" >> "$TMP"
		echo "<img src='$BOARD-bottom.png' width=32%>" >> "$TMP"
		if(-e "$BOARD-alt.png") then
			echo -n "<img src='$BOARD-alt.png' width=32%>" >> "$TMP"
			echo -n "<img src='$BOARD-alt-90.png' width=32%>" >> "$TMP"
			echo "<img src='$BOARD-alt-bottom.png' width=32%>" >> "$TMP"
			endif
		if(-e "$BOARD-panel.png") then
			echo -n "<img src='$BOARD-panel.png' width=49%>" >> "$TMP"
			echo "<img src='$BOARD-panel-bottom.png' width=49%>" >> "$TMP"
		endif
	end
endif
echo "" >> "$TMP"
echo "---" >> "$TMP"
echo "" >> "$TMP"
echo "*Auto generated $RM `date +%FT%T`*" >> "$TMP"
mv -f "$TMP" "$RM"
