#!/bin/csh -f
# Render images for a PCB
setenv BASE "$1:r"
setenv TMP `mktemp -u`.kicad_pcb
$0:h/clean -i "$BASE.kicad_pcb" -o "$TMP"
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb render -o "$BASE.png" "$TMP" --perspective --rotate ' -40,0,30' --zoom=0.85 --floor --pan ' -0.9,2.3,0' --width=2300 --height=1900 --background=opaque
$0:h/clean -i "$BASE.kicad_pcb" -o "$TMP" --case=2
if(! $status) then
	mv -f "$BASE.png" "$BASE-panel.png"
endif
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb render -o "$BASE.png" "$TMP" --perspective --rotate ' -40,0,30' --zoom=0.85 --floor --pan ' -0.9,2.3,0' --width=2300 --height=1900 --background=opaque
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb render -o "$BASE-90.png" "$TMP" --perspective --rotate ' -40,0,-60' --zoom=0.85 --floor --pan ' -0.9,2.3,0' --width=2300 --height=1900 --background=opaque
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb render -o "$BASE-bottom.png" "$TMP" --perspective --rotate ' -40,180,-30' --zoom=0.85 --floor --pan ' -0.9,2.3,0' --width=2300 --height=1900 --background=opaque
setenv RM "$BASE:h/README.md"
if(! -e "$RM") then
	echo "# $BASE:h:t" > "$RM"
	echo "" >> "$RM"
	echo "\![Top]($BASE:t.png)" >> "$RM"
	echo "\![Top rotated]($BASE:t-90.png)" >> "$RM"
	echo "\![Bottom]($BASE:t-bottom.png)" >> "$RM"
	if(-e "$BASE-panel.png") then
		echo "\![Panel]($BASE:t-panel.png)" >> "$RM"
	endif
endif
rm -f "$TMP"
